apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::334613583680:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::334613583680:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RU0WO1EXJ0QF
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-24T18:27:03Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-03-24T18:27:03Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl
    operation: Update
    time: "2021-03-24T20:43:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "24486"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 52382f08-9f5a-4d7d-b548-e08f73f6aa1b
